# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b4abefa643033c022c7727ab754ae55afe2bc9638e7ed2ca30f3367eed69e4f217d4f4a02e2b5749a953e3984d098e9906b00f4164d5c52d69c770966937f00

test:
  secret_key_base: ca67832b92906f82a0db8f53a9f0076025247a23f121e02ddfcd106dcd666d31c96ea088ca83e77ac5ea1387ef6d581195fdbbb4c265047399b76ad05224e091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
